name: Test Suite

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.1, 8.2, 8.3 ]
        stability: [ prefer-lowest, prefer-stable ]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, exif, iconv, fileinfo
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute Tests
        run: composer run test