name: Test Suite

on:
  push:
    branches:
      - develop
      - master
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        illuminate: [ 10, 11, 12 ]
        exclude:
          - php: 8.1
          - illuminate: 10

    name: Run Tests - PHP ${{ matrix.php }} - Illuminate ${{ matrix.illuminate }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, exif, iconv, fileinfo
          tools: composer
          coverage: xdebug

      - name: Install Composer Dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --with="illuminate/support=^${{ matrix.illuminate }}"

      - name: Execute Tests
        run: composer run test

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}